language: php
php:
  - 5.5
  - 5.4
  - hhvm
  
install:
  - composer self-update
  - composer install

services:
  - memcached
  - mongodb
  
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongo phpunit --eval 'db.addUser("unit", "test");'

script: vendor/bin/phpunit
