language: php
php:
  - 5.5
  - 5.4
  - hhvm
  
install:
  - composer self-update
  - composer install

services:
  - mongodb
  
before_script:
  - mongo phpunit --eval 'db.addUser("unit", "test");'

script: vendor/bin/phpunit
